function run_reproduction()
%RUN_REPRODUCTION Reproduce all quantitative tables and figures.
%
% Population simulation for Figure S9 is disabled by default because it is
% computationally expensive. On the author's 2023 MacBook, it takes about
% 10 minutes. When disabled, Figure S9 uses the population simulation CSV
% files previously generated by this repository and stored in results/.

RUN_POPULATION_SIMULATIONS = false;

repoRoot = fileparts(mfilename('fullpath'));
originalDirectory = pwd;
cleanup = onCleanup(@() cd(originalDirectory));
cd(repoRoot);

% Use the repository-local compphysiol toolbox and CNS templates/databases.
dependencyRoot = fullfile(repoRoot,'code','dependencies');
addpath(genpath(fullfile(dependencyRoot,'compphysiol','toolbox')));
addpath(genpath(fullfile(dependencyRoot,'cns')));
addpath(fullfile(repoRoot,'code','utilities'));

fprintf('\n=== Model development and tables ===\n');
runScript(repoRoot,'code/analysis/fit_tsinman_pampa_model.m');
runScript(repoRoot,'code/tables/generate_table_s5.m');
runScript(repoRoot,'code/tables/generate_table_s1.m');
runScript(repoRoot,'code/tables/generate_table_s2.m');
runScript(repoRoot,'code/tables/generate_table_s4.m');
runScript(repoRoot,'code/tables/generate_table_1.m');

fprintf('\n=== Main individual simulations and Table S3 ===\n');
mainSimulationScripts = [ ...
    "generate_figure_4_ethanol_simulations.m", ...
    "generate_figure_4_diazepam_simulations.m", ...
    "generate_figure_4_paracetamol_simulations.m", ...
    "generate_figure_4_ibuprofen_simulations.m", ...
    "generate_figure_4_indomethacin_simulations.m", ...
    "generate_figure_4_mannitol_simulations.m"];
for script = mainSimulationScripts
    runScript(repoRoot,"code/simulations/"+script);
end

fprintf('\n=== Main figures ===\n');
runScript(repoRoot,'code/figures/generate_figure_3.m');
runScript(repoRoot,'code/figures/generate_figure_4.m');
runScript(repoRoot,'code/analysis/calculate_figure_5_fold_errors.m');
runScript(repoRoot,'code/figures/generate_figure_5.m');

fprintf('\n=== Supplementary figures S1 and S3-S8 ===\n');
runScript(repoRoot,'code/figures/generate_figure_s1.m');
runScript(repoRoot,'code/figures/generate_figures_s3_s8.m');

fprintf('\n=== Supplementary Figure S9 ===\n');
if RUN_POPULATION_SIMULATIONS
    runScript(repoRoot,'code/simulations/generate_figure_s9_population_simulations.m'); %#ok<UNRCH>
else
    fprintf(['Skipping Figure S9 population simulations. Using the files previously ' ...
        'generated in results/simulations/supplementary_figures/figure_s9.\n']);
end
runScript(repoRoot,'code/figures/generate_figure_s9.m');

fprintf('\n=== Supplementary Figure S10 ===\n');
runScript(repoRoot,'code/simulations/generate_figure_s10_surface_area_simulations.m');
runScript(repoRoot,'code/figures/generate_figure_s10.m');

fprintf('\n=== Supplementary Figures S11 and S12 ===\n');
runScript(repoRoot,'code/analysis/calculate_figures_s11_s12_exposure_metrics.m');
runScript(repoRoot,'code/analysis/calculate_figures_s11_s12_fold_changes.m');
runScript(repoRoot,'code/figures/generate_figures_s11_s12.m');

fprintf('\n=== Supplementary Figure S13 ===\n');
runScript(repoRoot,'code/simulations/generate_figure_s13_paracetamol_iv_po_simulations.m');
runScript(repoRoot,'code/figures/generate_figure_s13.m');

fprintf('\n=== Supplementary Figures S14 and S15 ===\n');
runScript(repoRoot,'code/figures/generate_figure_s14.m');
runScript(repoRoot,'code/simulations/generate_figure_s15_model_simulations.m');
runScript(repoRoot,'code/analysis/calculate_figure_s15_summary.m');
runScript(repoRoot,'code/figures/generate_figure_s15.m');

fprintf('\n=== Final table validation ===\n');
validate_manuscript_tables;
fprintf('\nReproduction completed successfully.\n');
end

function runScript(repoRoot,relativePath)
file = fullfile(repoRoot,relativePath);
assert(isfile(file),'Required reproduction script was not found: %s',file);
fprintf('\nRunning %s\n',relativePath);
escapedFile = replace(string(file),"'","''");
evalin('base',"run('"+escapedFile+"')");
end
