%% Generate Table S1: physiological CNS PBPK model parameters

clear; clc;

scriptDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(fileparts(scriptDir));
inputFile = fullfile(repoRoot, 'data', 'model_parameters', ...
    'table_s1_base_parameters.csv');
outputDir = fullfile(repoRoot, 'results', 'tables');
outputFile = fullfile(outputDir, 'table_s1.csv');

if ~isfile(inputFile)
    error('Required parameter file was not found: %s', inputFile);
end
if ~exist(outputDir, 'dir')
    mkdir(outputDir);
end

base = readtable(inputFile, 'TextType', 'string');
value = @(name) base.Value(base.Parameter == name);

% Volumes
V_brt = value("brain_tissue_volume");
V_brb = value("brain_blood_volume");
V_bra = V_brt + V_brb;
V_ecv = V_bra * value("endothelial_fraction_of_total_brain");
V_csf = V_bra * value("csf_fraction_of_total_brain");
V_ccsf = V_csf * value("cranial_fraction_of_total_csf");
V_scsf = V_csf * (1 - value("cranial_fraction_of_total_csf"));
V_brm = V_bra - V_ecv - V_brb - V_csf;
V_ecf = V_brm * value("brain_ecf_fraction");
V_icf = V_brm * (1 - value("brain_ecf_fraction"));

% Flows
Q_cbf = value("cerebral_blood_flow");
Q_prod = value("csf_production_rate");
Q_bulk = Q_prod * value("bulk_flow_fraction");
Q_ssink = Q_prod * value("spinal_sink_fraction");
Q_csink = Q_prod - Q_ssink;
Q_sout = Q_ssink * value("spinal_outflow_fraction");
Q_sinflow = Q_ssink + Q_sout;

% Surface areas
SA_bbb = value("bbb_surface_area");
SA_bcsfb = SA_bbb * value("bcsfb_to_bbb_surface_area_ratio");
SA_bcm = SA_bbb * value("bcm_to_bbb_surface_area_ratio");

Category = [repmat("Volumes",10,1); repmat("Flows",7,1); ...
    repmat("Surface areas",3,1); repmat("pH",4,1)];
Parameter = ["V_brt";"V_brb";"V_bra";"V_ecv";"V_csf";"V_ccsf"; ...
    "V_scsf";"V_brm";"V_ecf";"V_icf"; ...
    "Q_cbf";"Q_prodflow";"Q_bulk";"Q_ssink";"Q_csink"; ...
    "Q_sout";"Q_sinflow";"SA_bbb";"SA_bcsfb";"SA_bcm"; ...
    "pH_brp";"pH_csf";"pH_ecf";"pH_icf"];
Description = ["Brain tissue volume";"Brain blood volume"; ...
    "Total brain volume";"Endothelial cell volume";"Total CSF volume"; ...
    "Cranial CSF volume";"Spinal CSF volume";"Brain mass volume"; ...
    "Brain extracellular fluid volume";"Brain intracellular fluid volume"; ...
    "Cerebral blood flow";"CSF production rate";"Bulk CSF flow rate"; ...
    "Spinal CSF sink flow";"Cranial CSF sink flow";"Spinal CSF outflow"; ...
    "Spinal CSF inflow";"Surface area of the blood-brain barrier"; ...
    "Surface area of the blood-CSF barrier"; ...
    "Surface area of the brain cell membrane";"pH of brain plasma"; ...
    "pH of cerebrospinal fluid";"pH of brain extracellular fluid"; ...
    "pH of brain intracellular fluid"];
DisplayValue = ["1.45";"0.064";sprintf("%.2f",V_bra);sprintf("%.4f",V_ecv); ...
    sprintf("%.2f",V_csf);sprintf("%.2f",V_ccsf);sprintf("%.3f",V_scsf); ...
    sprintf("%.2f",V_brm);sprintf("%.2f",V_ecf);sprintf("%.2f",V_icf); ...
    "46.8";"0.021";sprintf("%.4f",Q_bulk);sprintf("%.4f",Q_ssink); ...
    sprintf("%.3f",Q_csink);sprintf("%.4f",Q_sout);sprintf("%.3f",Q_sinflow); ...
    sprintf("%.0f",SA_bbb);sprintf("%.1f",SA_bcsfb);sprintf("%.0f",SA_bcm); ...
    string(value("brain_plasma_pH"));string(value("csf_pH")); ...
    string(value("brain_ecf_pH"));string(value("brain_icf_pH"))];
Unit = [repmat("L",10,1);repmat("L/h",7,1);repmat("m^2",3,1); ...
    repmat("pH",4,1)];
Reference = ["ICRP Publication 89";"ICRP Publication 89";"--"; ...
    "Simcyp; Verscheijden et al. 2019"; ...
    "Simcyp; Verscheijden et al. 2019"; ...
    "Simcyp; Verscheijden et al. 2019"; ...
    "Simcyp; Verscheijden et al. 2019"; ...
    "Simcyp; Verscheijden et al. 2019";"Saleh et al. 2021"; ...
    "Saleh et al. 2021";"ICRP Publication 89"; ...
    repmat("Simcyp; Verscheijden et al. 2019",6,1); ...
    "Gaohua et al. 2016; Saleh et al. 2021"; ...
    "Bowman et al. 2023; Gaohua et al. 2016"; ...
    "Bowman et al. 2023; Saleh et al. 2021"; ...
    "Atherton 2003; Saleh et al. 2021"; ...
    repmat("Fridén et al. 2011; Saleh et al. 2021",3,1)];
Note = ["Derived from ICRP Table 2.8 assuming a density of 1 kg/L"; ...
    "Derived from ICRP Tables 2.12 and 2.14";"V_bra = V_brt + V_brb"; ...
    "V_ecv = V_bra * 0.005";"V_csf = V_bra * 0.105"; ...
    "V_ccsf = V_csf * 0.8";"V_scsf = V_csf * 0.2"; ...
    "V_brm = V_bra - V_ecv - V_brb - V_csf";"V_ecf = V_brm * 0.2"; ...
    "V_icf = V_brm * 0.8";"Derived from ICRP Tables 2.39 and 2.40";"--"; ...
    "Q_bulk = Q_prodflow * 0.25; CV = 8%"; ...
    "Q_ssink = Q_prodflow * 0.38; CV = 30%"; ...
    "Q_csink = Q_prodflow - Q_ssink"; ...
    "Q_sout = Q_ssink * 0.9; CV = 100%"; ...
    "Q_sinflow = Q_ssink + Q_sout";"--";"SA_bcsfb = SA_bbb * 0.5"; ...
    "SA_bcm = SA_bbb * 20";"--";"--";"--";"--"];

tableS1 = table(Category,Parameter,Description,DisplayValue,Unit,Reference,Note);
writetable(tableS1, outputFile);

disp(tableS1)
fprintf('Saved %s\n', outputFile);
