%% Generate Figures S3-S8: compound-specific concentration-time profiles
% Each compound is exported as a separate figure on a linear concentration
% scale. Simulation inputs are generated by the Figure 4 workflows.

clear; clc; close all;

% -------------------------------------------------------------------------
% GLOBAL FIGURE STYLE PARAMETERS (CPT:PSP journal compliant)
% -------------------------------------------------------------------------

FIG_WIDTH  = 17.8;   % cm
FIG_HEIGHT = 18;     % cm

AXIS_LINE_WIDTH = 1.5;

LINE_WIDTH_MAIN = 2.5;
LINE_WIDTH_SIM  = 2.5;

MARKER_SIZE = 7.5;
DATA_LINE_WIDTH = 1.5;

X_TICK_FONT = 10;
Y_TICK_FONT = 10;

AXIS_LABEL_FONT = 10;
TITLE_FONT = 10;
PLASMA_LEGEND_FONT = 10;

MAIN_LEGEND_FONT = 10;
LINE_WIDTH_SIM_LEGEND = 1.5;


% -------------------------------------------------------------------------
% Legend location per compound (plasma panels)
% -------------------------------------------------------------------------

% legendLocationMap = containers.Map( ...
% {'Ethanol','Paracetamol','Mannitol','Ibuprofen','Diazepam','Indomethacin'}, ...
% {'northeast','southwest','southeast','southeast','southeast','southeast'} );

legendLocationMap = containers.Map( ...
{'Ethanol','Paracetamol','Mannitol','Ibuprofen','Diazepam','Indomethacin'}, ...
{'northeast','northeast','northeast','northeast','northeast','northeast'} );

% -------------------------------------------------------------------------
% Paths
% -------------------------------------------------------------------------

scriptDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(fileparts(scriptDir));
clinicalDataDir = fullfile(repoRoot,'data','clinical','figure_4');
simulationDataDir = fullfile(repoRoot,'results','simulations', ...
    'main_figures','figure_4');
outputDir = fullfile(repoRoot,'results','figures','supplementary');
if ~exist(outputDir,'dir'), mkdir(outputDir); end

% -------------------------------------------------------------------------
% Style configuration
% -------------------------------------------------------------------------

colorMap = containers.Map( ...
{'optimized','perfusion-limited','in situ perfusion','in vitro cell-based','in vitro PAMPA', ...
'in silico perfusion','in silico PAMPA'}, ...
{[0 0 0], [0 0 0], [0.9255 0.0039 0.0039], [0 0.4235 0.9451], [0 0.4745 0], ...
[0.9255 0.0039 0.0039], [0 0.4745 0]} );

lineStyleMap = containers.Map( ...
{'optimized','perfusion-limited','in situ perfusion','in vitro cell-based','in vitro PAMPA', ...
'in silico perfusion','in silico PAMPA'}, ...
{'-','--','-','-','-','--','--'} );

legendOrder = { ...
'optimized','perfusion-limited','in situ perfusion', ...
'in vitro cell-based','in vitro PAMPA','in silico perfusion','in silico PAMPA'};

expMarkers = {'o','^','s'};

% -------------------------------------------------------------------------
% Compound configuration
% -------------------------------------------------------------------------

% compounds = {
% 'Ethanol'      'g/L'     9    0   2      3   'brain mass'  0:2:8     [1e-2 1e-1 1e0 1e1]
% 'Diazepam'     'ng/mL'   25   0   300    1   'scsf'        0:4:24    [1e-2 1e0 1e2 1e4 1e6]
% 'Paracetamol'  'mg/L'    13   0   40     3   'scsf'        0:2:12    [1e-2 1e0 1e2]
% 'Ibuprofen'    'ng/mL'   25   0   2500   1   'scsf'        0:4:24    [1e-2 1e0 1e2 1e4 1e6]
% 'Indomethacin' 'ng/mL'   25   0   4000   1   'scsf'        0:4:24    [1e-2 1e0 1e2 1e4 1e6]
% 'Mannitol'     'g/L'     7    0   4.5    1   'scsf'        0:2:6     [1e-3 1e-1 1e1]
% };

compounds = {
% Figure Compound      Unit      xmax  plasmaYmax  brainYmax  nExp  brainDataSite xticks
  3      'Ethanol'      'g/L'      9      2         2           3    'brain mass'  0:2:8
  4      'Diazepam'     'ng/mL'   25    300         6           1    'scsf'        0:4:24
  5      'Paracetamol'  'mg/L'    13     40         25          3    'scsf'        0:2:12
  6      'Ibuprofen'    'ng/mL'   25   2500         15          1    'scsf'        0:4:24
  7      'Indomethacin' 'ng/mL'   25   4000         15          1    'scsf'        0:4:24
  8      'Mannitol'     'g/L'      7     4.5        0.5         1    'scsf'        0:2:6
};

sim_sites = {'plasma','brain ECF','sCSF'};
titles    = {'Plasma','Brain ECF','CSF'};

% -------------------------------------------------------------------------
% Main loops
% -------------------------------------------------------------------------

for c = 1:size(compounds,1)


% compound      = compounds{c,1};
% unit          = compounds{c,2};
% xmax          = compounds{c,3};
% ymax          = compounds{c,5};
% nExp          = compounds{c,6};
% brainDataSite = compounds{c,7};
% xticks_vals   = compounds{c,8};

figureNumber = compounds{c,1};
compound      = compounds{c,2};
unit          = compounds{c,3};
xmax          = compounds{c,4};

plasmaYmax    = compounds{c,5};
brainYmax     = compounds{c,6};

nExp          = compounds{c,7};
brainDataSite = compounds{c,8};
xticks_vals   = compounds{c,9};

% ---------------------------------------------------------------------
% Create figure (2x2 layout)
% ---------------------------------------------------------------------

figure
set(gcf,'Units','centimeters','Position',[2 2 FIG_WIDTH FIG_HEIGHT])

tl = tiledlayout(3,1,...
    'TileSpacing','compact',...
    'Padding','compact');

ax1 = nexttile(1);   % Plasma
ax2 = nexttile(2);   % Brain ECF
ax3 = nexttile(3);   % CSF

axesList = {ax1,ax2,ax3};

% ---------------------------------------------------------------------
% Read data
% ---------------------------------------------------------------------

dataFile = fullfile(clinicalDataDir,sprintf('%s_clinical_data.csv',compound));
simFile = fullfile(simulationDataDir,sprintf('%s_simulations.csv',compound));
if ~isfile(dataFile)
    error('Required clinical data file was not found: %s',dataFile);
end
if ~isfile(simFile)
    error(['Required generated simulation file was not found: %s\n' ...
        'Run the corresponding Figure 4 simulation workflow first.'],simFile);
end

Tdata = readtable(dataFile);

opts = detectImportOptions(simFile);
opts = setvartype(opts,3,"char");
Tsim = readtable(simFile,opts);

if ismember('source',Tsim.Properties.VariableNames)
    Tsim.source(strcmp(Tsim.source,'in vitro MDCK/UC')) = {'in vitro cell-based'};
    Tsim.source(strcmp(Tsim.source,'in vitro Caco-2')) = {'in vitro cell-based'};
end

% ---------------------------------------------------------------------
% Loop sites
% ---------------------------------------------------------------------

for s = 1:3

    ax = axesList{s};
    hold(ax,'on')

    sim_site = sim_sites{s};

    % -----------------------------------------------------------------
    % Experimental data
    % -----------------------------------------------------------------

    plotExp = false;

    if strcmp(sim_site,'plasma')
        plotExp = true;
        dataSite = 'plasma';
    end

    if strcmp(sim_site,'brain ECF') && strcmp(brainDataSite,'brain mass')
        plotExp = true;
        dataSite = 'brain mass';
    end

    if strcmp(sim_site,'sCSF') && strcmp(brainDataSite,'scsf')
        plotExp = true;
        dataSite = 'scsf';
    end

    if plotExp

        Tbl = Tdata(strcmpi(Tdata.site,dataSite),:);
        expSources = unique(Tbl.source);

        for k = 1:min(length(expSources),nExp)

            R = Tbl(strcmp(Tbl.source,expSources{k}),:);

            if ismember('sd_down',Tbl.Properties.VariableNames)

                errorbar(ax,...
                    R.time,...
                    R.conc,...
                    R.sd_down,...
                    R.sd_up,...
                    'k',...
                    'LineStyle','none',...
                    'LineWidth',DATA_LINE_WIDTH,...
                    'HandleVisibility','off');

            end

            plot(ax,...
                R.time,...
                R.conc,...
                'Marker',expMarkers{k},...
                'MarkerSize',MARKER_SIZE,...
                'MarkerFaceColor','none',...
                'MarkerEdgeColor','k',...
                'LineStyle','none',...
                'LineWidth',DATA_LINE_WIDTH,...
                'DisplayName',expSources{k});

        end

    end

    % -----------------------------------------------------------------
    % Simulations
    % -----------------------------------------------------------------

    Sim = Tsim(strcmpi(Tsim.site,sim_site),:);

    if strcmp(sim_site,'plasma')

        plot(ax,...
            Sim.time,...
            Sim.conc,...
            'k',...
            'LineWidth',LINE_WIDTH_MAIN,...
            'HandleVisibility','off');

    else

        for l = 1:length(legendOrder)

            src = legendOrder{l};
            SrcTbl = Sim(strcmp(Sim.source,src),:);

            if isempty(SrcTbl)
                continue
            end

            col = colorMap(src);
            ls  = lineStyleMap(src);

            PS_values = unique(SrcTbl.PS);

            for p = 1:length(PS_values)

                R = SrcTbl(SrcTbl.PS==PS_values(p),:);

                plot(ax,...
                    R.time,...
                    R.conc,...
                    'Color',col,...
                    'LineStyle',ls,...
                    'LineWidth',LINE_WIDTH_SIM,...
                    'HandleVisibility','off');

            end

        end

    end

    % -----------------------------------------------------------------
    % Plasma legend
    % -----------------------------------------------------------------

    if strcmp(sim_site,'plasma')

        lg_loc = legendLocationMap(compound);

        lg = legend(ax,...
            'Location',lg_loc,...
            'FontSize',PLASMA_LEGEND_FONT,...
            'Box','on');


    end

    % -----------------------------------------------------------------
    % Axis formatting
    % -----------------------------------------------------------------

    set(ax,'YScale','linear','LineWidth',AXIS_LINE_WIDTH)

    ax.XAxis.FontSize = X_TICK_FONT;
    ax.YAxis.FontSize = Y_TICK_FONT;
    ax.YMinorTick = 'off';

    xlim(ax, [0 xmax])
    %ylim(ax, [0 ymax])

    if strcmp(sim_site,'plasma')
        ylim(ax,[0 plasmaYmax])
    elseif strcmp(compound, 'Mannitol') && strcmp(sim_site,'brain ECF')
        ylim(ax,[0 plasmaYmax])
    else 
        ylim(ax,[0 brainYmax])
    end


    xticks(ax,xticks_vals)

    xlabel(ax,'Time (h)','FontSize',AXIS_LABEL_FONT)
    ylabel(ax,['Concentration (' unit ')'],'FontSize',AXIS_LABEL_FONT)

    title(ax,[compound ' — ' titles{s}],...
        'FontSize',TITLE_FONT,...
        'FontWeight','bold')

    box(ax,'on')

end

legendHandles = gobjects(1,length(legendOrder));

for l = 1:length(legendOrder)

    src = legendOrder{l};

    legendHandles(l) = plot(...
        NaN,NaN,...
        'Color',colorMap(src),...
        'LineStyle',lineStyleMap(src),...
        'LineWidth',LINE_WIDTH_SIM_LEGEND);
end

lgdTop = legend(legendHandles,...
    legendOrder,...
    'Orientation','horizontal',...
    'FontSize',MAIN_LEGEND_FONT,...
    'Box','on');

lgdTop.ItemTokenSize = [20 5];   % compact legend lines
lgdTop.NumColumns = 4;
lgdTop.Layout.Tile = 'north';

% ---------------------------------------------------------------------
% Export PDF
% ---------------------------------------------------------------------

set(gcf,'PaperUnits','centimeters')
set(gcf,'PaperPosition',[0 0 FIG_WIDTH FIG_HEIGHT])
set(gcf,'PaperSize',[FIG_WIDTH FIG_HEIGHT])

baseName = sprintf('Figure_S%d_%s',figureNumber,compound);
pdfFile = fullfile(outputDir,[baseName '.pdf']);
pngFile = fullfile(outputDir,[baseName '.png']);
print(gcf,pdfFile,'-dpdf','-vector')
exportgraphics(gcf,pngFile,'Resolution',600)

fprintf('Saved %s\n',pdfFile);
fprintf('Saved %s\n',pngFile);

close(gcf)


end
