function tableS3Ethanol = build_table_s3_ethanol( ...
    tableS3BaseFile, tableS1File, fitResultFile, settingsFile)
%BUILD_TABLE_S3_ETHANOL Assemble the Ethanol column of Table S3.

base = readStringTable(tableS3BaseFile);
physiology = readtable(tableS1File, 'TextType', 'string');
fit = readtable(fitResultFile, 'TextType', 'string');
settings = readStringTable(settingsFile);

textValue = @(name) base.Value(base.Parameter == name);
numberValue = @(name) str2double(textValue(name));
physValue = @(name) physiology.Value(physiology.Parameter == name);
settingValue = @(name) str2double(settings.Value(settings.Parameter == name));

MW = numberValue("MW");
logP = numberValue("logP");
ionicClass = textValue("ionic_class");
BP = 1 / numberValue("plasma_to_blood_ratio");
PS_BBB = fit.OptimizedPS_BBB_L_per_h(1);
SA_BBB = physValue("bbb_surface_area");
PS_BCSFB = PS_BBB * physValue("bcsfb_to_bbb_surface_area_ratio");
PS_BCM = PS_BBB * physValue("bcm_to_bbb_surface_area_ratio");
PS_E = settingValue("PS_ependyma");
P0 = PS_BBB / (0.036 * SA_BBB);

Category = [repmat("Physicochemical",4,1); repmat("Blood binding",3,1); ...
    repmat("Brain binding",4,1); repmat("Brain ionization",4,1); ...
    repmat("Brain permeability",5,1)];
Parameter = ["MW";"logP";"Class";"pKa";"BP";"EP";"fu_plasma"; ...
    "fu_brain_plasma";"fu_brain_ECF";"fu_brain_ICF";"fu_CSF"; ...
    "fn_brain_plasma";"fn_brain_ECF";"fn_brain_ICF";"fn_CSF"; ...
    "P0";"PS_BBB";"PS_BCSFB";"PS_BCM";"PS_E"];
Description = ["Molecular weight"; ...
    "Octanol-water partition coefficient of the neutral species"; ...
    "Ionic class";"Acid dissociation constant"; ...
    "Blood-to-plasma ratio";"Erythrocyte-to-plasma ratio"; ...
    "Fraction unbound in plasma";"Fraction unbound in brain plasma"; ...
    "Fraction unbound in brain ECF";"Fraction unbound in brain ICF"; ...
    "Fraction unbound in CSF";"Fraction neutral in brain plasma"; ...
    "Fraction neutral in brain ECF";"Fraction neutral in brain ICF"; ...
    "Fraction neutral in CSF";"Intrinsic permeability"; ...
    "Permeability-surface area product (BBB)"; ...
    "Permeability-surface area product (BCSFB)"; ...
    "Permeability-surface area product (BCM)"; ...
    "Permeability-surface area product (ependyma)"];
ExactValue = [MW;logP;NaN;NaN;BP;NaN;numberValue("fu_plasma"); ...
    numberValue("fu_brain_plasma");numberValue("fu_brain_ecf"); ...
    numberValue("fu_brain_icf");numberValue("fu_csf"); ...
    numberValue("fn_brain_plasma");numberValue("fn_brain_ecf"); ...
    numberValue("fn_brain_icf");numberValue("fn_csf"); ...
    P0;PS_BBB;PS_BCSFB;PS_BCM;PS_E];
DisplayValue = [sprintf("%.2f",MW);sprintf("%.2f",logP);ionicClass;"--"; ...
    sprintf("%.2f",BP);"--";repmat("1",9,1);sprintf("%.0f",P0); ...
    sprintf("%.0f",PS_BBB);sprintf("%.0f",PS_BCSFB); ...
    sprintf("%.0f",round(PS_BCM,-1));sprintf("%.0f",PS_E)];
Unit = ["g/mol";"unitless";"unitless";"unitless";"unitless"; ...
    "unitless";repmat("unitless",9,1);"1e-6 cm/s";repmat("L/h",4,1)];

tableS3Ethanol = table(Category,Parameter,Description,ExactValue, ...
    DisplayValue,Unit);
end

function data = readStringTable(file)
opts = detectImportOptions(file);
opts = setvartype(opts, opts.VariableNames, 'string');
data = readtable(file, opts);
end
